name: Minecraft 24/7 Server

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"

jobs:
  minecraft:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    timeout-minutes: 360

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install Java + Tools
      run: |
        sudo apt update
        sudo apt install openjdk-21-jdk screen zip unzip wget git -y

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Create Server Folder
      run: |
        mkdir server
    - name: Download Latest Paper Server
      run: |
        cd server
        VERSION="1.21.1"
        BUILD=$(curl -s https://api.papermc.io/v2/projects/paper/versions/$VERSION | \
        grep -o '"builds":[^]]*' | grep -o '[0-9]\+' | tail -1)

        wget https://api.papermc.io/v2/projects/paper/versions/$VERSION/builds/$BUILD/downloads/paper-$VERSION-$BUILD.jar -O paper.jar

        echo "eula=true" > eula.txt
   

    - name: Restore World Backup
      run: |
          if [ -f world-backup/world.zip ]; then
            unzip world-backup/world.zip -d server/
          fi

    - name: Install Playit Tunnel
      run: |
          wget https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux-amd64
          chmod +x playit-linux-amd64
 
    - name: Start Minecraft Server
      run: |
        cd server
        java -Xmx4G -Xms2G -jar paper.jar nogui &
        cd ..
        sleep 20
        ./playit-linux-amd64

    - name: Auto Backup System
      run: |
        while true
        do
          sleep 600
          cd server
          zip -r world.zip world
          mv world.zip ../world-backup/world.zip
          cd ..
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add world-backup/world.zip
          git commit -m "Auto backup" || true
          git push
        done
